# Generated by Django 4.2.8 on 2024-03-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oeb_open_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labour',
            old_name='number_of_employees_charged_to_operations_maintenance_and_administration',
            new_name='number_of_employees_charged_to_om_and_admin',
        ),
    ]
