# Generated by Django 4.2.8 on 2024-03-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uose', '0003_rdstextmodel_search_vector_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatorApplicaations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100)),
                ('application_start_date', models.DateField()),
                ('appl_description', models.CharField(max_length=250)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_detail', to='uose.entity')),
            ],
        ),
    ]
