# Generated by Django 4.2.8 on 2024-03-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uose', '0005_regulatorapplicaations_appl_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegulatorApplicaations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uose.regulatorapplicaations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntityDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uose.entitydocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
