# Generated by Django 4.2.8 on 2024-03-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uose', '0007_usernotesentitydocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(max_length=4, unique=True)),
                ('client_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserInboxMessageType',
            fields=[
                ('message_type', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('message_type_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserInbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_date', models.DateField()),
                ('message_text', models.TextField()),
                ('mark_as_read', models.BooleanField(default=False)),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uose.userinboxmessagetype')),
                ('receiving_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to=settings.AUTH_USER_MODEL)),
                ('sending_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEntityDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uose.client')),
                ('entity_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uose.entitydocument')),
            ],
        ),
    ]
