# Generated by Django 4.2.8 on 2024-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uose', '0008_client_userinboxmessagetype_userinbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotesentitydocuments',
            name='page_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotesentitydocuments',
            name='text_reference',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
