# Generated by Django 4.2.8 on 2024-03-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uose', '0009_usernotesentitydocuments_page_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinbox',
            name='entity_doc_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uose.entitydocument'),
            preserve_default=False,
        ),
    ]
